version: '3'

services:
  pyramid:
    build: ./pyramidProject
    ports:
      - "5000:5000"
    volumes:
      - ./pyramidProject:/pyramidProject
    command: >
      sh -c "pip install -e . && pserve development.ini --reload"

  client:
    container_name: "client"
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/client
      - /client/node_modules
    depends_on:
      - pyramid

  admin:
    container_name: "admin"
    build:
      context: ./admin/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./admin/:/admin
      - /admin/node_modules
    depends_on:
      - pyramid

